### ISSUE TITLE
my server crashed after i tried to get into the portal

### ISSUE THREAD

**Issue by BreastFire** [Nyphet/nightworld#10]
### I have confirmed no other issue reports this bug

- [X] I have searched for existing issues

### I have confirmed the mod is installed on the proper side

- [X] I have installed the mod properly

### Current behavior

Java 1.20.1 Fabric

### Expected behavior

that the mod works, because it´s looks fantastic

### Steps to reproduce

enter the world,
create the portal 
light them up

### Minecraft version

1.20.1

### Mod loader version

Fabric

### Mod version

v2.0.1

### Other mods

![mods](https://github.com/user-attachments/assets/00d063e9-cf82-49c4-84b6-85c2b9a849c2)

**Comment by Crystal-Spider** [comment]
If your game crashed, please provide the crash log

**Comment by BreastFire** [comment]
i can´t i deleted 2 days ago, and the log r lost

**Comment by Crystal-Spider** [comment]
Then, please, replicate the issue and send the new crash log.  
I tried to replicate, but I faced no issue, so without a crash log I can't help much.

**Comment by BreastFire** [comment]
no problem. i will

**Comment by Crystal-Spider** [comment]
I added the _pending_ label to show this issue is waiting for the logs.

**Comment by Crystal-Spider** [comment]
Ehy, do you have any update? Did you manage to get the logs?

**Comment by BreastFire** [comment]
no sorry i close my server, my friends left me haha, anyway close the
threat when i start again i try the server again i will make the test

tk sorry for waste ur time
