### ISSUE TITLE
Custom Portal Frame?

### ISSUE THREAD

**Issue by Dumpling00** [Nyphet/nightworld#11]
### I have confirmed no other issue asks the same question

- [X] I have searched for existing issues

### Question

Hello! Big fan of the mod. I was wondering if there's any way we could change the type of block needed for the portal frame via datapack, please.

**Comment by Crystal-Spider** [comment]
We will add a new block tag, and then check for the portal frame will be done using that block tag.

By default, the block tag will include Vanilla Crying Obsidian only.

We will also update the mod info (just the readme I guess) to highlight this functionality.

**Comment by Crystal-Spider** [comment]
The feature has been implemented, but has been moved to a different mod that works as an API to add any custom dimension and portal frame, while working server side, with just the dimension JSONs and the block tag for the portal frame.

We are currently on vacation, but in around 1 week we'll be back to work! Please, be patient until then!

**Comment by Crystal-Spider** [comment]
The other mod is ready for 1.21, we need to backport it to older versions too, and then we can release it along with a new Nightworld version that uses it.
It should be ready either by this weekend or the next one

**Comment by Dumpling00** [comment]
Awesome! Thank you so much ❤️

**Comment by Dumpling00** [comment]
Bit last minute actually (I apologize) But any chance we could change the igniter item and portal color too?

**Comment by Crystal-Spider** [comment]
Unfortunately, since this mod is server side only, it's not possible to change the color, which is be a client sided feature.
Using an item tag to tweak which items ignite the portal is theoretically possible, but due to the use of Vanilla Nether portals (which is mandatory to make this mod server-sided only) it's not actually feasible because Nether portals leverage on fire rather than the item.

**Comment by Crystal-Spider** [comment]
The [other mod](https://github.com/Crystal-Nest/server-sided-portals) is currently under review on Modrinth, as soon as it'll be available there I will release Nightworld new versions using it and that allow tweaking of the portal frame block via datapack.

To change the portal frame block you'll simply have to create a datapack and put, under the `server_sided_portals` namespace, a block tag called `nightworld.json` and list the block(s) you want the portal frame to be made of.

**Comment by Crystal-Spider** [comment]
Implemented with v4.0.0
