### ISSUE TITLE
Crash during boot up sequence on 1.20.1

### ISSUE THREAD

**Issue by Devilswarchild** [Nyphet/nightworld#12]
### I have confirmed no other issue reports this bug

- [X] I have searched for existing issues

### I have confirmed the mod is installed on the proper side

- [X] I have installed the mod properly

### Current behavior

crashing during the bootup sequence

### Expected behavior

not to crash

### Minecraft version

1.20.1

### Mod loader version

Forge 47.3.5

### Mod version

2.0.1

### Other mods

MineColonies: Dimensional Adventure Modpack

modlist is listed at the tail end of the crash report

### Stacktrace and logs

[Crash Report](https://mclo.gs/nWjienR)

modlist is at the end of the report

**Comment by Devilswarchild** [comment]
downgraded to the 2.0.0 version, got to the menu but the second I tried to load a save it crashed with the same error as well

**Comment by Crystal-Spider** [comment]
Thanks, we'll look into it as soon as we're back from vacation (~1 week).

**Comment by Crystal-Spider** [comment]
I think the problem is an incompatibility with [Canary](https://modrinth.com/mod/canary).

Luckily, the fix should be simple: just disable [fast portals](https://github.com/AbdElAziz333/Canary/wiki/Configuration-File#mixinaipoifast_portals).  
Let me know if it works!
