### ISSUE TITLE
Portal doesn't work

### ISSUE THREAD

**Issue by MrUnusual** [Nyphet/nightworld#3]
I created a portal using crying obsidian and used flint and steel to try to activate it, but only a blue flame appears in the portal frame, the portal doesn't appear. I'm using the 1.20.4 Fabric Loader.

**Comment by Crystal-Spider** [comment]
Do you have any other mods installed?  
Did you make sure you downloaded the correct version of the mod?

**Comment by MrUnusual** [comment]
I am using the 1.20.4 version. I do have other mods installed as well, is there a compatibility list? I have the tempad mod, the ad astro mod and the immersive portals mod

**Comment by Crystal-Spider** [comment]
There is a compatibility list right on the mod description, section "Compatibilities".  
Immersive Portals is not compatible (but it might be in the future)

**Comment by MrUnusual** [comment]
Oh ok, thank you
